CREATE TABLE MEMBER(
    ID VARCHAR2(30) PRIMARY KEY,
    PW VARCHAR2(30),
    AGE NUMBER(3),
    EMAIL VARCHAR2(30)
);cdss

SELECT * FROM MEMBER; --이클립스에서 JDBCInsert 한 후 실행시키기(update한후도 해보기)

INSERT INTO MEMBER VALUES('AAA', 'AAA', 10, 'AAA');
INSERT INTO MEMBER VALUES('BBB', 'BBB', 10, 'BBB');
INSERT INTO MEMBER VALUES('CCC', 'CCC', 10, 'CCC');
INSERT INTO MEMBER VALUES('DDD', 'DDD', 10, 'DDD');

COMMIT;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE EMPLOYEE_ID = 100;


